default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Fakebook_development

test:
  <<: *default
  database: Fakebook_test

production:
  <<: *default
  database: Fakebook_production
  username: bboylen
  password: 